### ISSUE TITLE
Add LKJCorrCholesky distribution

### ISSUE THREAD

**Issue by fehiepsi** [elbamos/pyro#1]
@elbamos I make a TODO list here to make it easier to track things:

- [x] Implement details for constraint class  @fehiepsi
- [x] Support batches for transforms @fehiepsi
- [x] Add tests for constraint, tanh transform  @fehiepsi 
- [x] Add test for PartialCorrToCorrCholeskyTransform
- [x] Add test for biject_to, transform_to with composed transform  @fehiepsi 
- [ ] Add test for distribution class
- [ ] Support batches for distribution's method
- [ ] Make an example for doing inference using this distribution.

**Comment by fehiepsi** [comment]
@elbamos I don't think that your last commit passes the test which I made. Could you please open PRs instead of pushing directly to LKJ branch, so I can comment on your changes?

**Comment by elbamos** [comment]
Yes, I can do that. Sorry about the etiquette breach. I think you see the point of what I did. Do you want to try to fix it or should I?

**Comment by elbamos** [comment]
Update: I spent a good amount of time converting this to work on batches. The code now runs, but the transformed matrix isn't right; possibly I implemented the wrong algorithm (you may remember our discussion about which page of the Stan manual to be looking at). I'll work on that this week, and will make a PR when I've done so.

Someone more experienced than I am with pyro is going to have to check to see if I've properly understood what's a `batch_shape`, `event_shape`, and `sample_shape`. 

Also -- on the transform, do we need to write a function for the log absolute determinant of the inverse of the transform?

**Comment by fehiepsi** [comment]
@elbamos Hope that the last PR solves all problems with Transform classes. With your last week's effort, I think you already know how to support "batching".

I'd tried to vectorize the transform's method but can not find a good way to avoid the loop in `__call__`. Let's leave it as it is (unless you come up with a clever idea to solve it). I think we have almost done. Let's add tests for distribution class and make a PR to pyro when you are ready. Note that pyro has moved to a new place: https://github.com/pyro-ppl/pyro

**Comment by elbamos** [comment]
There's definitely no way to avoid the loop.  

Like I said, I'll go through this tomorrow.

**Comment by elbamos** [comment]
I'm sorry that you were unhappy with my comments on your code submission. There's still a bunch of work to be done...

**Comment by fehiepsi** [comment]
Our approaches are different. I don't know what I should do. If I add tests, how can I know if my tests are not wrong given a non-working code? The easiest way is to fix the code. Then if I fix it, how can I make sure that it won't affect performance, as you claimed in your comments? I don't know why you can't just address performance based on that PR later, but keep asking me to address performance issues (without evidence in code...).

> There's still a bunch of work to be done...

Can I know what they are? I guess the remaining work is to add tests for distribution class? You can test your log_prob implementation against log_prob of https://pytorch.org/docs/stable/distributions.html#transformeddistribution (indeed you can make your LKJ distribution a subclass of a transformed distribution); test for the mean of the distribution is an identity matrix; make sure that batch shape is correct for both sample and log_prob methods.

**Comment by elbamos** [comment]
The code is now all working, thank you very much.

The way to help is by submitting PRs that attempt to address individual issues.  When someone submits a monolithic PR that tries to re-write many things at the same time, that's very hard to review.  Its too common that you end up with a mixed bag of changes that work, changes that are bad ideas, changes that don't work, and changes that just reflect someone's preferences. That creates a big problem for review, which is what took place here. 

Here are a few things that need doing:
1. Tests for the numerical accuracy of the log determinants.
2. Tests for the numerical accuracy of the log prob; these should either use the interval method or a known-correct source like an existing implementation.
3. During MCMC, the HMC class emits an error about not being able to get a valid trace.  Its not clear why.
4. Writing an example. 

Please note that any new code cannot rely on batched tril/triu - if you rely on that behavior, the PR could not be merged because it would then create a dependency on the unreleased version of pytorch.

**Comment by fehiepsi** [comment]
It seems like I am contributing to your own property, where you can define all criterion you want, rather than compromise and praise other's work. Do you recognize that you use a lot of terminology such as: "pretty sure faster", "definitely no way", "do you see the point", "too common", "big problem", "all working",... without evidence (or I am so stupid to understand). The way you work is quite strange to me. Of course, that's your style. But I won't work with that style. And I regret that I have spent much of my time to explain things for you without a thank for it.

I just want to give my reason to stop this collaboration. Please keep up with your work.

**Comment by elbamos** [comment]
I was trying to encourage you to reconsider things so you could fix them yourself and have the credit for it. 

You claimed to have discovered a "bug" which was actually your own mathematical error. When I tried to point this out to you, you took it as a personal slight.

And the code you submitted didn't work.  Ok, I will move on.

**Comment by fehiepsi** [comment]
> You claimed to have discovered a "bug" which was actually your own mathematical error.

Please look at your implementation before justifying things. So it is not a bug from Stan but a bug from your code (sorry, it is my mistake to point out the wrong source of the bug) or your wrong understanding of arguments in `log_abs_det_jabcobian` method. I corrected it in my comment (used `x.cosh()` instead of `y.cosh()`) and didn't want to mention that source to keep the discussion going on.

> And the code you submitted didn't work.

Fine, another claim without evidence. Didn't work with your system I guess. If it is because of PyTorch version, then you can ask me why it didn't work in your system... I believed that there were still missing points in my code, so I have asked your opinion on which tests else to add to verify things... As I said, your way of working is quite difference from me. So I will just simply ignore your claims for the best of my life. :+1: 

About credit, I mean credit from you, not from other people. Maybe your way of communication is quite strange to me. I didn't have my own motivation to work on this project. And when you said you wanted to do it, my only motivation is to help you... until when you keep asking me to address your improvements without evidence. After I spent a good amount of time to explain them, then you just ignore them (because I didn't see any word saying something like "thank for your explanation, I get it now,..."; not even the simplest one :+1: sign to let me know that you get it) and claimed that it was hard to review.

To encourage you on this project, I recommend you look at other implementation in PyTorch/Pyro's distribution to put a correct argument to your distribution method. As usual, you should add tests for things that you claimed that you have tested it. No one can understand what is going on with your MCMC run and point out the source of the bug for you if you keep giving your "claiming" style. Hope it help!
